version: '3'

services:
  db:
    build:
      context: ./docker/db/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    container_name: db
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
