GET http://localhost:8080/api/users/search
Accept: application/json

###
GET http://localhost:8080/api/users/search?name=テスト
Accept: application/json

###
GET http://localhost:8080/api/users/auth
Authorization: Basic 1 22222

### 1:11111をBase64にエンコード
GET http://localhost:8080/api/users/auth
Authorization: Basic MToxMTExMQ==

###
