GET http://localhost:8080/api/users/search
Accept: application/json

###
GET http://localhost:8080/api/users/search?name=テスト
Accept: application/json

###
GET http://localhost:8080/api/users/auth
Authorization: Basic 2 22222

###
GET http://localhost:8080/api/users/auth
Authorization: Basic dXNlcjpwYXNzd2Q=

###
